import 'package:flutter/foundation.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';

/// Function signatures for signaling callbacks to be wired into your Firestore/Socket layer.
typedef OnIceCandidateCallback = void Function(RTCIceCandidate candidate);
typedef OnTrackCallback = void Function(MediaStream stream);

class WebRTCService {
  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;
  MediaStream? _remoteStream;

  // Audio/Video state toggles
  bool _isMicOn = true;
  bool _isCameraOn = true;
  bool _isSpeakerOn = false;

  // Configuration for WebRTC Connection (STUN servers are crucial for NAT traversal)
  final Map<String, dynamic> _configuration = {
    'iceServers': [
      {
        'urls': [
          'stun:stun1.l.google.com:19302',
          'stun:stun2.l.google.com:19302',
        ]
      }
    ]
  };

  // Media constraints for full-quality audio/video
  final Map<String, dynamic> _mediaConstraints = {
    'audio': true,
    'video': {
      'mandatory': {
        'minWidth': '640',
        'minHeight': '480',
        'minFrameRate': '30',
      },
      'facingMode': 'user',
      'optional': [],
    }
  };

  // Getters for UI layer and BLoC
  MediaStream? get localStream => _localStream;
  MediaStream? get remoteStream => _remoteStream;
  bool get isMicOn => _isMicOn;
  bool get isCameraOn => _isCameraOn;
  bool get isSpeakerOn => _isSpeakerOn;

  /// Initializes the local media stream (Camera and Microphone)
  /// and attaches it to the provided local renderer.
  Future<void> openUserMedia(
      RTCVideoRenderer localRenderer,
      ) async {
    try {
      _localStream = await navigator.mediaDevices.getUserMedia(_mediaConstraints);
      localRenderer.srcObject = _localStream;
    } catch (e) {
      debugPrint('Error opening user media: $e');
      rethrow;
    }
  }

  /// Creates and configures the RTCPeerConnection instance.
  Future<void> createPeerConnectionInstance({
    required RTCVideoRenderer remoteRenderer,
    required OnIceCandidateCallback onIceCandidate,
    required OnTrackCallback onTrackAdded,
  }) async {
    try {
      _peerConnection = await createPeerConnection(_configuration);

      // Register local stream tracks to the peer connection
      _localStream?.getTracks().forEach((track) {
        _peerConnection?.addTrack(track, _localStream!);
      });

      // Handle ICE Candidates generated by the local WebRTC stack
      _peerConnection?.onIceCandidate = (RTCIceCandidate candidate) {
        debugPrint('Generated Local ICE Candidate: ${candidate.candidate}');
        onIceCandidate(candidate);
      };

      // Handle connection state changes (Useful for updating BLoC states)
      _peerConnection?.onConnectionState = (RTCPeerConnectionState state) {
        debugPrint('WebRTC Connection State Changed: $state');
      };

      // Handle incoming remote media tracks
      _peerConnection?.onTrack = (RTCTrackEvent event) {
        debugPrint('Remote Track Received: ${event.track.kind}');
        if (event.streams.isNotEmpty) {
          _remoteStream = event.streams[0];
          remoteRenderer.srcObject = _remoteStream;
          onTrackAdded(_remoteStream!);
        }
      };
    } catch (e) {
      debugPrint('Error creating peer connection: $e');
      rethrow;
    }
  }

  /// **Caller Flow**: Generates an SDP Offer to initiate the call.
  Future<RTCSessionDescription> createOffer() async {
    if (_peerConnection == null) {
      throw StateError('PeerConnection is not initialized.');
    }

    try {
      RTCSessionDescription offer = await _peerConnection!.createOffer({
        'offerToReceiveAudio': true,
        'offerToReceiveVideo': true,
      });

      await _peerConnection!.setLocalDescription(offer);
      debugPrint('Local Offer Description Set Successfully');
      return offer;
    } catch (e) {
      debugPrint('Error creating WebRTC offer: $e');
      rethrow;
    }
  }

  /// **Receiver Flow**: Generates an SDP Answer in response to a caller's offer.
  Future<RTCSessionDescription> createAnswer(RTCSessionDescription remoteOffer) async {
    if (_peerConnection == null) {
      throw StateError('PeerConnection is not initialized.');
    }

    try {
      // Step 1: Set the remote party's offer as the Remote Description
      await _peerConnection!.setRemoteDescription(remoteOffer);

      // Step 2: Generate the matching answer
      RTCSessionDescription answer = await _peerConnection!.createAnswer({
        'offerToReceiveAudio': true,
        'offerToReceiveVideo': true,
      });

      // Step 3: Commit the answer locally
      await _peerConnection!.setLocalDescription(answer);
      debugPrint('Local Answer Description Set Successfully');
      return answer;
    } catch (e) {
      debugPrint('Error creating WebRTC answer: $e');
      rethrow;
    }
  }

  /// Sets the remote answer received from the signaling server (Caller perspective).
  Future<void> setRemoteDescription(RTCSessionDescription remoteAnswer) async {
    try {
      await _peerConnection?.setRemoteDescription(remoteAnswer);
      debugPrint('Remote Answer Description Set Successfully');
    } catch (e) {
      debugPrint('Error setting remote description: $e');
    }
  }

  /// Injects a remote ICE candidate provided by the signaling server into the connection.
  Future<void> addRemoteIceCandidate(RTCIceCandidate candidate) async {
    try {
      await _peerConnection?.addCandidate(candidate);
      debugPrint('Remote ICE Candidate Added Successfully');
    } catch (e) {
      debugPrint('Error adding remote ICE candidate: $e');
    }
  }

  // ===========================================================================
  // Media Controls (Hardware Interfacing)
  // ===========================================================================

  /// Toggles the microphone on or off.
  void toggleMic() {
    if (_localStream != null) {
      _isMicOn = !_isMicOn;
      for (var track in _localStream!.getAudioTracks()) {
        track.enabled = _isMicOn;
      }
    }
  }

  /// Toggles the video camera feed on or off.
  void toggleCamera() {
    if (_localStream != null) {
      _isCameraOn = !_isCameraOn;
      for (var track in _localStream!.getVideoTracks()) {
        track.enabled = _isCameraOn;
      }
    }
  }

  /// Flips between the front-facing and rear-facing cameras.
  Future<void> switchCamera() async {
    if (_localStream != null && _localStream!.getVideoTracks().isNotEmpty) {
      try {
        final videoTrack = _localStream!.getVideoTracks().first;
        await Helper.switchCamera(videoTrack);
        debugPrint('Camera switched successfully');
      } catch (e) {
        debugPrint('Error switching camera: $e');
      }
    }
  }

  /// Switches audio output route between Earpiece and Speakerphone.
  void toggleSpeaker() {
    _isSpeakerOn = !_isSpeakerOn;
    Helper.setSpeakerphoneOn(_isSpeakerOn);
    debugPrint('Speakerphone set to: $_isSpeakerOn');
  }

  // ===========================================================================
  // Cleanup & Resource Disposal
  // ===========================================================================

  /// Terminates the active session and cleanly disposes of all hardware resources.
  Future<void> dispose() async {
    debugPrint('Disposing WebRTC Service resources...');

    // 1. Stop all tracks in the local stream to turn off camera hardware lights
    _localStream?.getTracks().forEach((track) {
      track.stop();
    });
    await _localStream?.dispose();
    _localStream = null;

    // 2. Clear remote stream tracks
    _remoteStream?.getTracks().forEach((track) {
      track.stop();
    });
    await _remoteStream?.dispose();
    _remoteStream = null;

    // 3. Close the peer connection
    await _peerConnection?.close();
    _peerConnection = null;
  }
}